name: nanoprobe
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

executables:
  nprobe:

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  cli_util: ^0.4.2
  collection: ^1.19.1
  file: ^7.0.1
  glob: ^2.1.3
  path: ^1.9.1
  pub_semver: ^2.2.0
  pubspec_parse: ^1.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
